# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Wagamart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up the Node.js version to be used
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies, build, and run tests
      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Zip the entire project for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip .

      # Upload the zipped artifact for use in the deployment job
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the zipped artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the downloaded artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Login to Azure using a publish profile (make sure you have this secret set in your GitHub repository)
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Wagamart'                    # Name of your Azure Web App
          slot-name: 'Production'                 # Deployment slot (Production, Staging, etc.)
          package: '.'                            # Path to the unzipped app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F478CC76B6A64619B93340504BF4A716 }}
