name: Build and deploy Node.js app to Azure Web App - Waga

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and start
        run: |
          npm install
          npm run build --if-present
          npm run start

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Check DNS resolution for Azure Web App
        run: |
          host waga.scm.azurewebsites.net

      - name: Test connectivity to Azure Web App
        run: |
          curl -v https://waga.scm.azurewebsites.net

      - name: 'Deploy to Azure Web App with Retry Logic'
        id: deploy-to-webapp
        run: |
          retries=3
          delay=10
          for attempt in $(seq 1 $retries); do
            echo "Deployment attempt $attempt of $retries..."
            if az webapp deployment source config-zip --resource-group Zobel --name Waga --src release.zip; then
              echo "Deployment succeeded."
              break
            else
              echo "Deployment failed."
              if [ $attempt -lt $retries ]; then
                echo "Retrying in $delay seconds..."
                sleep $delay
              else
                echo "All $retries attempts failed."
                exit 1
              fi
            fi
          done
